# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f08a8ef77083c99398a5bd793de88924766d51a1d8dda0263b635a040e1cd9281860c122604c18cab853986ff9f950bc14a820ea37571a8d0d0997bcb5ac0820

test:
  secret_key_base: 0fb8a83b5e11358fb704b979151c3a8810c0c6450b4178104f4148471118ebfc7e50e3dc1f8da702908634e9ec0569327d19cb97fdd81f878eb4071684a71f9e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
